export const alignments = {
  base: {
    around: "justify-around",
    between: "justify-between",
    center: "justify-center",
    end: "justify-end",
    evenly: "justify-evenly",
    start: "justify-start",
    stretch: "justify-stretch",
  },
  sm: {
    around: "sm:justify-around",
    between: "sm:justify-between",
    center: "sm:justify-center",
    end: "sm:justify-end",
    evenly: "sm:justify-evenly",
    start: "sm:justify-start",
    stretch: "sm:justify-stretch",
  },
  md: {
    around: "md:justify-around",
    between: "md:justify-between",
    center: "md:justify-center",
    end: "md:justify-end",
    evenly: "md:justify-evenly",
    start: "md:justify-start",
    stretch: "md:justify-stretch",
  },
  lg: {
    around: "lg:justify-around",
    between: "lg:justify-between",
    center: "lg:justify-center",
    end: "lg:justify-end",
    evenly: "lg:justify-evenly",
    start: "lg:justify-start",
    stretch: "lg:justify-stretch",
  },
  xl: {
    around: "xl:justify-around",
    between: "xl:justify-between",
    center: "xl:justify-center",
    end: "xl:justify-end",
    evenly: "xl:justify-evenly",
    start: "xl:justify-start",
    stretch: "xl:justify-stretch",
  },
} as const
